
<div style="display:block;clear:both;" class="behaviorchange-determinant-selection-table-start"></div>
<div class="behaviorchange-determinant-selection-table-container">

```{r, eval=TRUE, echo=FALSE}

oldKableViewOption <- getOption("kableExtra_view_html", NULL);
options(kableExtra_view_html = FALSE);

if (!exists('headingLevel') || !is.numeric(headingLevel) || (length(headingLevel) != 1)) {
  headingLevel <- 0;
}

```

```{r, results='asis', eval=TRUE}
ufs::heading("Determinant Selection Table",
             headingLevel=headingLevel);
```

```{r, echo=echoPartial, results='asis', eval=TRUE}

if (requireNamespace("kableExtra", quietly = TRUE)) {
  print(
    prettyDeterminantSelectionTable(
      x,
      digits=digits
    )
  );
} else {
  knitr::kable(x,
               digits=digits,
               row.names=FALSE);
}

```

```{r echo=FALSE}
if (!is.null(oldKableViewOption)) {
  options(kableExtra_view_html = oldKableViewOption);
}
```

</div>
<div style="display:block;clear:both;" class="behaviorchange-determinant-selection-table-end"></div>
