---
title: "Matrix van Aspecten van de Psychologie (MAP)"
author: "Gjalt-Jorn Peters & Rik Crutzen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Matrix van Aspecten van de Psychologie (MAP)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

De Matrix of Aspects of Psychology (MAP) is de naam voor een instrument dat gebruikt kan worden om twee dingen te doen: 

1. Alle geidentificeerde mogelijk relevante aspecten van de menselijke psychology op een rijtje zetten (dus beliefs, determinanten, etc) 

2. Gestructureerd onderbouwen waarom elk aspect wel of niet wordt geselecteerd. Aspecten die worden geselelecteerd worden geherformuleerd als Change Objectives en die aspecten vormen samen de Matrix of Change Objectives. Diezelfde aspecten (Change Objectives) komen vervolgens terug in kolom vier van de ABCD. 

Deze technologie is nog in ontwikkeling. Een voorbeeld van een MAP specificatie staat op https://r-packages.gitlab.io/behaviorchange/articles/matrices-of-change-objectives.html 

De behaviorchange_map specificatie laat zien hoe geidentificeerde aspecten kunnen worden gespecificeerd. Deze vallen altijd onder een subgedrag (een performance objective) en onder een determinant. Determinanten worden beschreven in DCT specificaties (zie https://a-bc.gitlab.io/dct-raa/ voor een voorbeeld in progress). Deze DCT specificaties kunnen kort zijn en kunnen ter plekke worden gedefinieerd, zodat ze later kunnen worden hergebruikt. 

Elk aspect heeft vervolgens een unieke identifier, een label, en een of meerdere bronnen, zodat duidelijk is waar ze vandaan komen. 

De behaviorchange_matrix_columns specificatie geeft aan welke determinanten de kolommen in de matrix moeten vormen. Omdat psychologische constructen hierarchisch zijn opgebouwd is het belangrijk om te specificeren op welke niveau van aggregatie de matrix moet worden geconstrueerd. Dit niveau is het niveau waarop de koppeling met gedragsveranderingprincipes plaatsvindt. 

Vervolgens wordt door middel van justifier documentatie van elk aspect aangegeven wat er mee gebeurd. Door hier gebruik te maken van de justifier specificatie kan eenvoudig in kaart worden gebracht welke beslissingen beter en slechter onderbouwd zijn. 

Deze beslissingen hebben allemaal het type "aspect_selection", moeten allemaal verwijzen naar de identifier van het betreffende aspect via "bc_map_id", en kunnen drie waarden hebben: "drop", "select", en "defer". Deze drukken respectievelijk de beslissing uit om de intervantie niet op een aspect te richten; om dat juist wel te doen; en om deze interventie niet op een aspect te richten, terwijl dat aspect wellicht wel relevant is. 

Conform de justifier conventie hebben beslissingen onderbouwingen, die gebaseerd zijn op assertions die bronnen hebben. Op deze manier is precies terug te vinden waarop elk besluit is gebaseerd. 

Deze specificaties bevatten dus zowel 1) alles dat bekend is over waarom mensen mogelijkerwijs het doelgedrag al dan niet uitvoeren; 2) de keuzes die worden gemaakt en de onderbouwingen van die keuzes; en als resultaat van de verwerking van die twee, 3) de matrix van veranderdoelen, die vervolgens de basis vormt van de ABCD. 


```
---
behaviorchange_map:
  sub_behavior:
    -
      id: po1
      label: "Buying condoms"
      determinant:
        -
          dct_id: instrumentalAttitude_73dnt5zb
          aspect:
            -
              id: aspect1
              label: "In my neighbourhood, you can only buy condoms at the 7/11, and I don't want people seeing me buying condoms there."
              source: some_source_id
---
```

```
---
behaviorchange_matrix_columns:
  - attitude_73dnt5zc
  - perceivedNorms_73dnt5zq
  - perceivedBehavioralControl_73dnt603
---
```



```
---
decision:
  -
    id: aspect1_decision
    type: aspect_selection
    bc_map_id: aspect1
    value: "forgo"
    justification:
      id: aspect1_justification
      label: "The CIBER plot shows that this belief is unlikely to be a strong predictor of behavior."
      assertion:
        id: ciberplot_1
        label: "This assertion is the CIBER plot as generated by the CIBER analysis script."
        source: ciber_analysis_script
  -
    id: aspect2_decision
    type: aspect_selection
    bc_map_id: aspect2
    value: "select"
    co_formulation: "... explains why condoms decrease the probability of pregnancy."
    justification:
      id: aspect3_justification
      label: "The CIBER plot shows that this belief is likely a very strong predictor of behavior."
      assertion:
        id: ciberplot_1
  -
    id: aspect3_decision
    type: aspect_selection
    bc_map_id: aspect3
    value: "defer"
    justification:
      id: aspect3_justification
      label: "The CIBER plot shows that this aspect is likely a reasonably strong predictor of behavior, but it is not feasible given available funds to target this aspect."
      assertion:
        id: ciberplot_1
---
```

